# Generated by Django 5.2.5 on 2025-08-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='slug',
        ),
    ]
